#!/bin/bash
# setup_env.sh - Environment setup for {{ cookiecutter.project_name }}
# Generated by cookiecutter-python-project
# DO NOT EDIT THIS FILE DIRECTLY - IT WILL BE OVERWRITTEN BY COOKIECUTTER

# --- Configuration ---
# These variables are populated by cookiecutter during project generation
PROJECT_NAME="{{ cookiecutter.project_name }}"
PROJECT_SLUG="{{ cookiecutter.project_slug }}"
PYTHON_VERSION="{{ cookiecutter.python_version }}"
AUTHOR_NAME="{{ cookiecutter.author_name }}"
AUTHOR_EMAIL="{{ cookiecutter.author_email }}"

# --- Constants ---
VERSION="0.1.0"
ENV_NAME="${PROJECT_SLUG}-dev"
ENV_PATH_DEV="${PWD}/dev-env"
ENV_PATH_PROD="${PWD}/prod-env"
ENV_PATH="${ENV_PATH_DEV}"

# --- Default values ---
RUN_TESTS=true
VERBOSE=false
FORCE=false
SKIP_CONDA=false
SKIP_PRE_COMMIT=false
SKIP_TESTS=false
SKIP_LOCK=false
DEV_MODE=false

# --- Command line arguments ---
# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-tests)
            SKIP_TESTS=true
            shift
            ;;
        --skip-conda)
            SKIP_CONDA=true
            shift
            ;;
        --skip-pre-commit)
            SKIP_PRE_COMMIT=true
            shift
            ;;
        --skip-lock)
            SKIP_LOCK=true
            shift
            ;;
        --dev)
            DEV_MODE=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -h|--help)
            echo "Setup script for ${PROJECT_NAME}"
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --no-tests          Skip running tests after setup"
            echo "  --skip-conda         Skip conda environment setup"
            echo "  --skip-pre-commit    Skip pre-commit installation"
            echo "  --skip-lock          Skip conda-lock generation"
            echo "  --dev                Use development environment"
            echo "  --force              Force operations that would normally prompt"
            echo "  -v, --verbose        Show more detailed output"
            echo "  -h, --help           Show this help message"
            echo ""
            echo "Environment will be created at: ${ENV_PATH}"
            exit 0
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-tests)
            RUN_TESTS=false
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--no-tests]"
            echo "  --no-tests     Skip running the test suite after setup"
            echo "  -h, --help     Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;

    esac
done

# Exit on error, unset variables, and pipe failures
set -euo pipefail

# Source utility functions
UTILS_SCRIPT="${BASH_SOURCE[0]%/*}/setup_utils.sh"
if [ ! -f "$UTILS_SCRIPT" ]; then
    echo -e "\033[1;31m✗ Error: Could not find setup_utils.sh\033[0m" >&2
    exit 1
fi
# shellcheck source=setup_utils.sh
source "$UTILS_SCRIPT"

# Enhanced logging
log() {
    local level=$1
    shift
    local message="[$(date +'%Y-%m-%d %H:%M:%S')] [${PROJECT_SLUG}] [$level] $*"
    case $level in
        debug)
            $VERBOSE && echo -e "${BLUE}${message}${NC}" >&2
            ;;
        info)
            echo -e "${BLUE}${message}${NC}"
            ;;
        success)
            echo -e "${GREEN}✓ ${message}${NC}"
            ;;
        warning)
            echo -e "${YELLOW}⚠️  ${message}${NC}" >&2
            ;;
        error)
            echo -e "${RED}✗ ${message}${NC}" >&2
            exit 1
            ;;
        *)
            echo "${message}" >&2
            ;;
    esac
}

# --- Main Script ---

log "info" "Starting ${PROJECT_NAME} environment setup"
log "debug" "Python version: ${PYTHON_VERSION}"
log "debug" "Environment path: ${ENV_PATH}"

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check for required commands
check_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        log "error" "Required command not found: $1"
    fi
}

# Verify required commands are available
for cmd in conda python pip; do
    check_command "$cmd"
done

# --- Main Script Logic ---

# Setup environment directory
if [ -d "${ENV_PATH}" ] && [ "${FORCE}" = false ]; then
    log "warning" "Environment already exists at ${ENV_PATH}"
    if [ -z "${CI:-}" ]; then  # Skip prompt in CI
        read -rp "Do you want to remove it and start fresh? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            log "info" "Removing existing environment..."
            rm -rf "${ENV_PATH}"
        else
            log "info" "Using existing environment"
        fi
    else
        log "info" "Running in CI, using existing environment"
    fi
fi

section "Setting up ${PROJECT_NAME} environment in ${ENV_PATH}"

# --- Conda Setup ---
setup_conda() {
    if [ "${SKIP_CONDA}" = true ]; then
        log "info" "Skipping conda setup as requested"
        return 0
    fi

    # Check if conda is available
    if ! command -v conda &> /dev/null; then
        log "warning" "Conda not found in PATH"
        
        # If we're in a container, try to install miniconda
        if [ -f /.dockerenv ] || grep -q docker /proc/1/cgroup 2>/dev/null; then
            install_conda_in_container
        else
            error "conda is not installed or not in PATH.\nPlease install Miniconda/Anaconda first: https://docs.conda.io/en/latest/miniconda.html"
        fi
    fi

    # Initialize conda for this shell
    log "info" "Initializing conda..."
    __conda_setup="$($(command -v conda) 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
        log "debug" "Conda shell integration initialized"
    else
        if [ -f "${CONDA_PREFIX:-/dev/null}/etc/profile.d/conda.sh" ]; then
            . "${CONDA_PREFIX}/etc/profile.d/conda.sh"
            log "debug" "Sourced conda.sh from ${CONDA_PREFIX}/etc/profile.d/"
        else
            export PATH="$(conda info --base)/bin:$PATH"
            log "warning" "Could not find conda.sh, added conda to PATH"
        fi
    fi
    unset __conda_setup

    # Verify conda is working
    if ! command -v conda &> /dev/null; then
        error "Failed to initialize conda. Please check your installation."
    fi

    log "success" "Conda initialized: $(conda --version 2>/dev/null || echo 'unknown version')"
}

# Install conda in a container environment
install_conda_in_container() {
    section "Installing Miniconda in container..."
    
    # Install wget if not available
    if ! command -v wget &> /dev/null; then
        log "info" "Installing wget..."
        if command -v apt-get &> /dev/null; then
            run_command_verbose apt-get update
            run_command_verbose apt-get install -y wget
        elif command -v yum &> /dev/null; then
            run_command_verbose yum install -y wget
        elif command -v apk &> /dev/null; then
            run_command_verbose apk add --no-cache wget
        else
            error "Could not install wget: package manager not found"
        fi
    fi
    
    # Download and install Miniconda
    local miniconda_installer="/tmp/miniconda.sh"
    local conda_prefix="/opt/conda"
    
    log "info" "Downloading Miniconda installer..."
    run_command_verbose wget -q "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(uname -m).sh" -O "$miniconda_installer"
    
    log "info" "Installing Miniconda to ${conda_prefix}..."
    run_command_verbose bash "$miniconda_installer" -b -p "$conda_prefix"
    run_command_verbose rm -f "$miniconda_installer"
    
    # Add conda to PATH
    export PATH="${conda_prefix}/bin:$PATH"
    
    # Verify installation
    if ! command -v conda &> /dev/null; then
        error "Failed to find conda after installation. PATH: $PATH"
    fi
    
    log "success" "Miniconda installed successfully: $(conda --version 2>/dev/null || echo 'unknown version')"
}

# --- Environment Management ---
create_environment() {
    if [ "${SKIP_CONDA}" = true ]; then
        log "info" "Skipping environment creation as requested"
        return 0
    fi

    # Check if environment already exists
    if [ -d "${ENV_PATH}" ]; then
        if [ "${FORCE}" = true ]; then
            log "warning" "Removing existing environment at ${ENV_PATH} (--force)"
            rm -rf "${ENV_PATH}"
        else
            log "info" "Using existing environment at ${ENV_PATH}"
            return 0
        fi
    fi

    # Create conda environment
    section "Creating conda environment"
    log "info" "Creating environment with Python ${PYTHON_VERSION}"
    
    run_command_verbose conda create -y -p "${ENV_PATH}" python="${PYTHON_VERSION}" || \
        error "Failed to create conda environment"
    
    # Initialize the new environment
    log "info" "Initializing new environment..."
    CONDA_BASE=$(conda info --base)
    source "${CONDA_BASE}/etc/profile.d/conda.sh"
    conda activate "${ENV_PATH}" || error "Failed to activate new environment"
    
    log "success" "Environment created at ${ENV_PATH}"
}

# --- Package Installation ---
install_packages() {
    section "Installing packages"
    
    # Ensure we're in the right environment
    local env_path=$(conda info --envs | grep -E "^${ENV_PATH}\s" | awk '{print $1}')
    if [ -z "${env_path}" ]; then
        error "Target environment not found. Please create it first."
    fi
    
    # Activate the environment
    CONDA_BASE=$(conda info --base)
    source "${CONDA_BASE}/etc/profile.d/conda.sh"
    conda activate "${ENV_PATH}" || error "Failed to activate environment"
    
    # Install development dependencies
    log "info" "Installing development dependencies..."
    
    # First install pip, setuptools, and wheel
    run_command_verbose conda install -y -c conda-forge pip setuptools wheel
    
    # Install the package in development mode with all extras
    log "info" "Installing package in development mode..."
    run_command_verbose pip install -e ".[dev]" || \
        error "Failed to install package in development mode"
    
    log "success" "Package installed in development mode"
}

# --- Pre-commit Setup ---
setup_pre_commit() {
    if [ "${SKIP_PRE_COMMIT}" = true ]; then
        log "info" "Skipping pre-commit setup as requested"
        return 0
    fi
    
    section "Setting up pre-commit hooks"
    
    # Check if pre-commit is installed
    if ! command -v pre-commit &> /dev/null; then
        log "info" "Installing pre-commit..."
        run_command_verbose conda install -y -c conda-forge pre-commit
    fi
    
    # Install pre-commit hooks
    log "info" "Installing pre-commit hooks..."
    run_command_verbose pre-commit install --install-hooks || \
        log "warning" "Failed to install some pre-commit hooks"
    
    log "success" "pre-commit hooks installed"
}

# --- Conda Lock Generation ---
generate_conda_lock() {
    if [ "${SKIP_LOCK}" = true ]; then
        log "info" "Skipping conda-lock generation as requested"
        return 0
    fi
    
    section "Generating conda-lock file"
    
    # Check if conda-lock is installed
    if ! command -v conda-lock &> /dev/null; then
        log "info" "Installing conda-lock..."
        run_command_verbose conda install -y -c conda-forge conda-lock
    fi
    
    # Determine platform
    local platform=""
    case "$(uname -s)" in
        Darwin*)
            if [ "$(uname -m)" = "arm64" ]; then
                platform="osx-arm64"
            else
                platform="osx-64"
            fi
            ;;
        Linux*)
            platform="linux-64"
            ;;
        *)
            log "warning" "Unsupported platform for conda-lock: $(uname -s)"
            return 1
            ;;
    esac
    
    log "info" "Generating lock file for platform: ${platform}"
    run_command_verbose conda-lock -f environment.yml -p "${platform}" --lockfile conda-lock.yml || \
        log "warning" "Failed to generate conda-lock file"
    
    log "success" "conda-lock file generated"
}

# --- Main Execution ---

# Run setup steps
setup_conda
create_environment
install_packages
setup_pre_commit
generate_conda_lock

# --- Post-Setup Information ---
section "${PROJECT_NAME} Setup Complete!"
echo -e "\n${GREEN}✓ Environment setup completed successfully!${NC}"
echo -e "\n${YELLOW}Next steps:${NC}"
echo -e "1. Activate the environment:"
echo -e "   ${BLUE}conda activate ${ENV_PATH}${NC}"
echo -e "2. Run the test suite:"
echo -e "   ${BLUE}pytest${NC}"
echo -e "3. Start developing!"

# Run tests if requested
if [ "${SKIP_TESTS}" = false ]; then
    section "Running tests"
    if command -v pytest &> /dev/null; then
        run_command_verbose pytest -v --cov=. --cov-report=term-missing
    else
        log "warning" "pytest not found. Install it with 'conda install pytest'"
    fi
fi

echo -e "\n${GREEN}Setup complete! Happy coding! 🚀${NC}"

# Environment file to use
log "info" "Determining which environment file to use"
ENV_FILE_DEV="${SCRIPT_DIR}/environment-dev.yml"
ENV_FILE_BASE="${SCRIPT_DIR}/environment.yml"
ENV_FILE_TO_USE=""

if [ "$DEV_MODE" = true ]; then
    ENV_FILE_TO_USE="${ENV_FILE_DEV}"
    ENV_PATH="${ENV_PATH_DEV}"
    echo -e "${YELLOW}Using development environment file: ${ENV_FILE_TO_USE##*/}${NC}"
elif [ -f "${ENV_FILE_DEV}" ]; then
    ENV_FILE_TO_USE="${ENV_FILE_DEV}"
    ENV_PATH="${ENV_PATH_DEV}"
    echo -e "${YELLOW}Using development environment file: ${ENV_FILE_TO_USE##*/}${NC}"
elif [ -f "${ENV_FILE_BASE}" ]; then
    ENV_FILE_TO_USE="${ENV_FILE_BASE}"
    ENV_PATH="${ENV_PATH_PROD}"
    echo -e "${YELLOW}Using base environment file: ${ENV_FILE_TO_USE##*/}${NC}"
else
    error "Neither development ('${ENV_FILE_DEV##*/}') nor base ('${ENV_FILE_BASE##*/}') environment file found in ${SCRIPT_DIR}"
fi

# Create or update environment in the selected directory
if [ ! -d "${ENV_PATH}" ]; then
    log "info" "Creating new conda environment at ${ENV_PATH}"
    section "Creating new environment from ${ENV_FILE_TO_USE##*/}"
    run_command_verbose conda env create -f "${ENV_FILE_TO_USE}" --prefix "${ENV_PATH}"
    if [ $? -eq 0 ]; then
        log "success" "Successfully created conda environment"
    else
        log "error" "Failed to create conda environment"
        exit 1
    fi
else
    log "info" "Updating existing conda environment at ${ENV_PATH}"
    section "Updating existing environment from ${ENV_FILE_TO_USE##*/}"
    run_command_verbose conda env update -f "${ENV_FILE_TO_USE}" --prefix "${ENV_PATH}" --prune
    if [ $? -eq 0 ]; then
        log "success" "Successfully updated conda environment"
    else
        log "error" "Failed to update conda environment"
        exit 1
    fi
fi

# Install project package and development tools
log "info" "Installing project package in development mode"
section "Installing project package and development tools into '${ENV_PATH}'"

log "info" "Running: conda run --prefix ${ENV_PATH} pip install -e ${SCRIPT_DIR}[dev]"
run_command_verbose conda run --prefix "${ENV_PATH}" pip install -e "${SCRIPT_DIR}[dev]"
if [ $? -eq 0 ]; then
    log "success" "Successfully installed project package in development mode"
else
    log "error" "Failed to install project package"
    exit 1
fi

log "info" "Setting up pre-commit hooks..."
if ! conda run --prefix "${ENV_PATH}" pre-commit --version &> /dev/null; then
    log "warning" "pre-commit not found in environment '${ENV_PATH}'. Installing..."
    run_command_verbose conda run --prefix "${ENV_PATH}" pip install pre-commit
    if [ $? -eq 0 ]; then
        log "success" "Successfully installed pre-commit"
    else
        log "error" "Failed to install pre-commit"
        exit 1
    fi
fi
log "info" "Installing pre-commit hooks..."
run_command_verbose conda run --prefix "${ENV_PATH}" pre-commit install --install-hooks
if [ $? -eq 0 ]; then
    log "success" "Successfully installed pre-commit hooks"
else
    log "warning" "Failed to install some pre-commit hooks (this might be expected in some environments)"
fi

section "Managing conda-lock.yml for reproducibility"
log "info" "Checking for conda-lock..."
if ! command -v conda-lock &> /dev/null; then
    log "warning" "conda-lock not found in PATH. Attempting to install..."
    if conda install -n base -y -c conda-forge conda-lock; then
        log "success" "Successfully installed conda-lock via conda"
    else
        log "warning" "Failed to install conda-lock via conda. Trying pip..."
        if pip install conda-lock; then
            log "success" "Successfully installed conda-lock via pip"
        else
            log "warning" "Failed to install conda-lock via pip. Skipping lock file generation."
        fi
    fi
    
    if ! command -v conda-lock &> /dev/null; then
        log "warning" "conda-lock still not available after installation attempts. Skipping lock file generation."
    fi
else
    log "info" "Found conda-lock: $(conda-lock --version 2>/dev/null || echo 'version unknown')"
fi

if command -v conda-lock &> /dev/null; then
    log "info" "Determining platform for conda-lock..."
    PLATFORM=""
    case "$(uname -s)" in
        Darwin*)
            if [ "$(uname -m)" = "arm64" ]; then 
                PLATFORM="osx-arm64"
                log "info" "Detected Apple Silicon (arm64) platform"
            else 
                PLATFORM="osx-64"
                log "info" "Detected Intel Mac platform"
            fi
            ;;
        Linux*) 
            PLATFORM="linux-64"
            log "info" "Detected Linux platform"
            ;;
        *) 
            log "warning" "Unsupported platform for conda-lock: $(uname -s)"
            ;;
    esac

    if [ -n "$PLATFORM" ]; then
        log "info" "Creating temporary environment file for conda-lock..."
        TEMP_ENV_FILE_FOR_LOCK="${SCRIPT_DIR}/.temp_env_for_lock.yml"
        
        # Create a clean copy without editable installs
        if ! cp "${ENV_FILE_TO_USE}" "${TEMP_ENV_FILE_FOR_LOCK}"; then
            log "error" "Failed to create temporary environment file"
            exit 1
        fi
        
        # Remove editable installs which can cause issues with conda-lock
        if ! sed -i.bak '/^[[:space:]]*-e[[:space:]]/d' "${TEMP_ENV_FILE_FOR_LOCK}" 2>/dev/null; then
            # Try without .bak for macOS
            if ! sed -i '' '/^[[:space:]]*-e[[:space:]]/d' "${TEMP_ENV_FILE_FOR_LOCK}" 2>/dev/null; then
                log "warning" "Failed to clean editable installs from temp file"
            fi
        fi
        
        # Clean up backup file if it exists
        rm -f "${TEMP_ENV_FILE_FOR_LOCK}.bak" 2>/dev/null || true

        log "info" "Generating conda-lock.yml for platform: $PLATFORM"
        LOCK_FILE_PATH="${SCRIPT_DIR}/conda-lock.yml"
        
        # Run conda-lock with verbose output
        log "info" "Running: conda-lock lock -f ${TEMP_ENV_FILE_FOR_LOCK} -p ${PLATFORM} --lockfile ${LOCK_FILE_PATH}"
        if conda-lock lock -f "${TEMP_ENV_FILE_FOR_LOCK}" -p "$PLATFORM" --lockfile "${LOCK_FILE_PATH}"; then
            log "success" "Successfully generated ${LOCK_FILE_PATH} for ${PLATFORM}"
        else
            log "warning" "Failed to generate conda-lock.yml"
        fi
        
        # Clean up temporary file
        rm -f "${TEMP_ENV_FILE_FOR_LOCK}"
    fi
else
    log "info" "Skipping conda-lock generation (not available)"
fi

section "Environment setup complete!"
echo -e "\n${GREEN}✓ Environment '${ENV_PATH}' is ready to use!${NC}"

section "Verification"
log "info" "Environment setup complete. Running verification..."

# Generate pre-commit config from template if needed
generate_precommit_config() {
    local template_file="${SCRIPT_DIR}/.pre-commit-config.template.yaml"
    local output_file="${SCRIPT_DIR}/.pre-commit-config.yaml"
    
    if [ ! -f "$template_file" ]; then
        log "warning" "Pre-commit template not found at $template_file"
        return 0
    fi
    
    # Only generate if output doesn't exist or template is newer
    if [ ! -f "$output_file" ] || [ "$template_file" -nt "$output_file" ]; then
        log "info" "Generating pre-commit configuration..."
        
        # Get conda prefix (base directory)
        local conda_prefix
        conda_prefix=$(conda info --base 2>/dev/null || echo "$HOME/anaconda3")
        
        # Create the pre-commit config from template
        if sed -e "s|{{CONDA_PREFIX}}|${conda_prefix}|g" \
               -e "s|{{ENV_PATH}}|${ENV_PATH}|g" \
               "$template_file" > "$output_file"; then
            log "success" "Generated pre-commit configuration at $output_file"
        else
            log "warning" "Failed to generate pre-commit configuration"
            return 1
        fi
    else
        log "info" "Pre-commit configuration is up to date"
    fi
}

# Generate the pre-commit config
generate_precommit_config

# Run tests if requested
if [ "$RUN_TESTS" = true ]; then
    log "info" "Running test suite using environment '${ENV_PATH}'..."
    if conda run --prefix "${ENV_PATH}" pytest -v --cov=. --cov-report=term-missing; then
        log "success" "All tests passed!"
    else
        log "warning" "Some tests failed. This might be expected depending on your setup."
        echo -e "\n${YELLOW}You can run the tests again later with:${NC}"
        echo -e "  conda activate \"${ENV_PATH}\" && pytest -v --cov=. --cov-report=term-missing"
    fi
else
    log "info" "Skipping test run as requested (--no-tests flag was used)."
fi

# Always show activation instructions
section "Environment Setup Complete"
log "success" "The project environment has been successfully configured!"

echo -e "\n${GREEN}Activation Instructions:${NC}"
echo -e "${YELLOW}To activate the environment, run:${NC}"
echo -e "  conda activate \"${ENV_PATH}\""

echo -e "\n${YELLOW}Or add this to your shell profile (e.g., .bashrc, .zshrc) for easier activation:${NC}"
echo -e "  alias activate_project='conda activate \"${ENV_PATH}\"'"

echo -e "\n${YELLOW}To verify the installation, run:${NC}"
echo -e "  pytest -v --cov=. --cov-report=term-missing"

echo -e "\n${GREEN}Happy coding! 🚀${NC}"
